"use client";

import { FormEvent, useState } from "react";
import { PageHero } from "@/components/page-parts";

export default function RequestTraining() {
  const [sent, setSent] = useState(false);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSent(true); }
  return <><PageHero eyebrow="Bring us to your group" title="Request a training session." text="Tell us a little about your audience and goals. Our student team will follow up to shape a session around your needs." /><section className="container form-layout section"><aside><h2>What to expect</h2><ol><li><b>Share your needs</b><span>Tell us about your group, timing, and topics.</span></li><li><b>Plan together</b><span>We’ll confirm availability and workshop details.</span></li><li><b>Learn hands-on</b><span>Our instructors bring the session to life.</span></li></ol><div className="contact-box"><span>Questions first?</span><a href="mailto:frontlinefirstaid@virginia.edu">frontlinefirstaid@virginia.edu</a></div></aside>{sent ? <div className="success"><span>✓</span><h2>Thanks for reaching out.</h2><p>Your request has been captured in this demo. Connect the form to your preferred email or form service before launch.</p><button className="text-link" onClick={() => setSent(false)}>Send another request →</button></div> : <form className="training-form" onSubmit={submit}><div className="field-row"><label>First name<input required name="firstName" placeholder="Jane" /></label><label>Last name<input required name="lastName" placeholder="Doe" /></label></div><label>Email address<input required type="email" name="email" placeholder="jane@example.org" /></label><label>Organization or group<input required name="organization" placeholder="Organization name" /></label><div className="field-row"><label>Estimated group size<select name="size" defaultValue=""><option value="" disabled>Select one</option><option>Under 10</option><option>10–25</option><option>26–50</option><option>More than 50</option></select></label><label>Preferred timeframe<input name="timeframe" placeholder="e.g. October 2026" /></label></div><fieldset><legend>What are you interested in?</legend><div className="checks"><label><input type="checkbox" name="topic" value="CPR" /> CPR fundamentals</label><label><input type="checkbox" name="topic" value="First aid" /> First aid essentials</label><label><input type="checkbox" name="topic" value="Custom" /> Custom workshop</label></div></fieldset><label>Anything else we should know?<textarea name="message" rows={5} placeholder="Tell us about your audience, goals, or accessibility needs." /></label><button className="button button-dark" type="submit">Submit request <span>→</span></button><small>This demo form does not send data yet.</small></form>}</section></>;
}
